version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: codenames-postgres
    environment:
      POSTGRES_DB: codenames
      POSTGRES_USER: codenames
      POSTGRES_PASSWORD: codenames123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/common/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: